### PR TITLE
fix resolve docker image name as transport

### LINKED ISSUE #2205: Can't use official docker images like docker:stable
Moving https://github.com/containers/libpod/issues/5391 reported by @zaro to Buildah for tracking as it's really a `buildah bud --layers` command issue:

/kind bug

Can't use the docker:stable ( docker:19.03 also fails ) image with latest podman.

**Steps to reproduce the issue:**

1. Create docker file

        echo 'FROM docker:stable' > Dockerfile

2. Try to build it

       $ podman build .
       STEP 1: FROM docker:stable
       Error: error creating build container: while pulling "docker:stable" as "stable": error parsing 
       attempted image name "docker:stable": docker: image reference stable does not start with //

**Describe the results you received:**
I get and error `Error: error creating build container: while pulling "docker:stable" as "stable": error parsing 
       attempted image name "docker:stable": docker: image reference stable does not start with //`

**Describe the results you expected:**

   I would expect the build to succeed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
∴ podman version
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
∴ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 242860032
  MemTotal: 8246157312
  OCIRuntime:
    name: crun
    package: crun-0.12.2.1-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.12.2.1
      commit: cd7cea7114db5f6aa35fbb69fa307c19c2728a31
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 15617748992
  SwapTotal: 15632166912
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: mi
  kernel: 5.5.7-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 1h 11m 36.69s (Approximately 0.04 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/zaro/.config/containers/storage.conf
  ContainerStore:
    number: 303
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/zaro/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 434
  RunRoot: /run/user/1000
  VolumePath: /home/zaro/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
∴ rpm -q podman
podman-1.8.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine with Fedora 31

In the comments thee, @vrothberg asked:

Hi @zaro, thanks for taking the time to open the issue. Can you try using FROM docker.io/library/docker:stable? This should work.

There must be a parsing bug in Buildah (Cc @TomSweeneyRedHat) that checks for docker: prefix instead of a docker:// prefix to match against the docker-transport in the containers/image library.

Which @zaro confirmed worked.

### PR DESCRIPTION
**Pull request by QiWang19**
fix #2205 Validate the supported transports to fix the corner case. Do not use docker as transport if `docker:` is Docker Official Image

Signed-off-by: Qi Wang <qiwan@redhat.com>

#### What type of PR is this?

 /kind bug

#### How to verify it
`$ buildah from docker:stable`
#### Which issue(s) this PR fixes:
#2205 

#### Does this PR introduce a user-facing change?
No

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

File: util/util.go [hunk 1]
```diff
@@ -148,6 +148,12 @@ func ResolveName(name string, firstRegistry string, sc *types.SystemContext, sto
 	return candidates, DefaultTransport, searchRegistriesAreEmpty, nil
 }
 
+// startsWithValidTransport validates the name starts with Buildah supported transport
+// to avoid the corner case image name same as the transport name
+func startsWithValidTransport(name string) bool {
```
Comment (TomSweeneyRedHat) [inline util/util.go:153]: We might want to make this global at some point.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests, which aren't too at the moment.

File: util/util.go (hunk 1 above)
Comment (QiWang19) [reply util/util.go]: fixed

**Comment by TomSweeneyRedHat** [comment]
bors retry
