### PR TITLE
`manifest add --artifact`: handle multiple values

### LINKED ISSUE #5727: Adding manifest does not work with multiple files
Hello,

the man page says the following for the `--artifact` option:

Create an artifact manifest and add it to the image index.  Arguments after the index name will be interpreted as file names rather than as image references. In most scenarios, the [--artifact-type](https://www.mankier.com/1/buildah-manifest-add#--artifact-type) option should also be specified.

This is now what I am seeing.

**Steps to reproduce the issue:**

One file works fine:

```
lzap@dev:~/netboot$ buildah manifest add --artifact quay.io/lzapletal/fedora-bootfiles:39 ./push.sh 
0e99b03ca288875b8d89619bd28000ce9f6efe773ff9bed522ef1ad3fbad01da: sha256:e4c18e89f69ddf54effd3f5b604ec2f6d75481b1c39eaacb808adea512890d40
```

Two or more:

```
lzap@dev:~/netboot$ buildah manifest add --artifact quay.io/lzapletal/fedora-bootfiles:39 ./push.sh ./renovate.json
Error: parsing reference "": repository name must have at least one component
```

**Describe the results you received:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```

buildah-1.37.1-1.fc40.x86_64
```

**Output of `buildah version`:**

```
buildah version 1.37.1 (image-spec 1.1.0, runtime-spec 1.2.0)
```

**Output of `cat /etc/*release`:**

```
Fedora release 40 (Forty)
NAME="Fedora Linux"
VERSION="40 (Forty)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Forty)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
Fedora release 40 (Forty)
```

**Output of `uname -a`:**

```
Linux dev.home.lan 6.10.6-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Aug 19 14:09:30 UTC 2024 x86_64 GNU/Linux
```

Observation: this works fine with podman, only buildah CLI is affected.

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Don't error out when `manifest add --artifact` is given multiple files, and add the test I should have added to check that.

#### How to verify it

New integration test!

#### Which issue(s) this PR fixes:

Fixes #5727.

#### Does this PR introduce a user-facing change?

```release-note
`buildah manifest add --artifact` no longer fails if it's invoked with multiple file arguments.  All of the files should be added to a single artifact manifest which should then be added to the image index being updated.
```

### CODE REVIEW

File: cmd/buildah/manifest.go [hunk 1]
```diff
@@ -446,6 +446,10 @@ func manifestAddCmd(c *cobra.Command, args []string, opts manifestAddOpts) error
 			}
 		}
 	default:
+		listImageSpec = args[0]
+		if listImageSpec == "" {
+			return fmt.Errorf(`Invalid image name "%s"`, args[0])
+		}
```
Comment (lzap) [inline cmd/buildah/manifest.go:452]: If this is the same code as case 2, could be converted to simple if check.

**Comment by lzap** [comment]
Thanks for looking into that, I was writing similar PR but you were faster :-)

Once this gets merged, is there a "development" container tag we can use until this gets into stable?

File: cmd/buildah/manifest.go [hunk 2]
```diff
@@ -432,25 +432,21 @@ func manifestAddCmd(c *cobra.Command, args []string, opts manifestAddOpts) error
...
+				}
 			}
 		}
-	default:
-		if opts.artifact {
-			artifactSpec = args[1:]
-		} else {
-			return errors.New("Too many arguments: expected list and image add to list")
-		}
 	}
```
Comment (lzap) [inline cmd/buildah/manifest.go:450]: This could have been just:

```
if len(args) < 2 {
  return errors.New("At least a list image and an image or artifact to add must be specified")
}

// the rest of the code - three idents saved
```

**Comment by nalind** [comment]
> Thanks for looking into that, I was writing similar PR but you were faster :-)
> 
> Once this gets merged, is there a "development" container tag we can use until this gets into stable?

The quay.io/buildah/upstream image should pick up changes before too long.  The git commit information is stored in the release field of the RPM that's built from upstream instead of in the binary itself, so it's not immediately obvious from the image's metadata.

**Comment by lzap** [comment]
Test are failing, these looks like relevant failures: `Error: parsing reference "": repository name must have at least one component`

**Comment by nalind** [comment]
@TomSweeneyRedHat any reason I shouldn't try to cherry-pick this for release-1.37?

**Comment by lzap** [comment]
Thanks for taking a look @nalind !

**Comment by TomSweeneyRedHat** [comment]
@nalind I'm late here, but the Buildah v1.37 branch is supposed to be closed unless there's a Jira card associated for the fix, or the fix is localized to Test code.
