### PR TITLE
Fix panic in --secret flag parsing when key has no value

### LINKED ISSUE #28394: panic after incorrect `--secret=id` parameter
### Issue Description

podman panics when providing an incomplete `--secret` parameter

### Steps to reproduce the issue

> podman --version
podman version 5.8.1
> # In a directory with a valid `Dockerfile`
> podman build --secret=id=,src .
panic: runtime error: index out of range [1] with length 1
...

### Describe the results you received

panic: runtime error: index out of range [1] with length 1

goroutine 13 [running]:
github.com/containers/buildah/pkg/parse.Secrets({0xc0006c2710, 0x1, 0x0?})
        github.com/containers/buildah/pkg/parse/parse.go:1091 +0x568
github.com/containers/buildah/imagebuildah.newExecutor(_, {_, _}, {_, _}, {{0x0, 0x0}, {0xc000116b80, 0x1c}, 0x0, ...}, ...)
        github.com/containers/buildah/imagebuildah/executor.go:200 +0x727
github.com/containers/buildah/imagebuildah.buildDockerfilesOnce({_, _}, {_, _}, _, {_, _}, {{0x0, 0x0}, {0xc000116b80, ...}, ...}, ...)
        github.com/containers/buildah/imagebuildah/build.go:429 +0x967
github.com/containers/buildah/imagebuildah.BuildDockerfiles.func2()
        github.com/containers/buildah/imagebuildah/build.go:269 +0x4cd
github.com/hashicorp/go-multierror.(*Group).Go.func1()
        github.com/hashicorp/go-multierror/group.go:23 +0x5f
created by github.com/hashicorp/go-multierror.(*Group).Go in goroutine 1
        github.com/hashicorp/go-multierror/group.go:20 +0x79

### Describe the results you expected

I did not expect a panic. Maybe an error if the parameter is mandatory.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.43.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.2.1-2.fc43.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.2.1, commit: '
  cpuUtilization:
    idlePercent: 99.84
    systemPercent: 0.1
    userPercent: 0.06
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: container
    version: "43"
  eventLogger: file
  freeLocks: 2048
  hostname: 75457642090f
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 1
      size: 999
    - container_id: 1000
      host_id: 1001
      size: 64535
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 1
      size: 999
    - container_id: 1000
      host_id: 1001
      size: 64535
  kernel: 6.6.87.2-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 6089797632
  memTotal: 8172826624
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    defaultNetwork: podman
    dns:
      package: aardvark-dns-1.17.0-1.fc43.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.17.0
    package: netavark-1.17.2-1.fc43.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.17.2
  ociRuntime:
    name: crun
    package: crun-1.25.1-1.fc43.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.25.1
      commit: 156ae065d4a322d149c7307034f98d9637aa92a2
      rundir: /tmp/storage-run-1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20260120.g386b5f5-1.fc43.x86_64
    version: |
      pasta 0^20260120.g386b5f5-1.fc43.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /tmp/storage-run-1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 2h 59m 11.00s (Approximately 0.08 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/podman/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/podman/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 29818691584
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /tmp/storage-run-1000/containers
  transientStore: false
  volumePath: /home/podman/.local/share/containers/storage/volumes
version:
  APIVersion: 5.8.1
  BuildOrigin: Fedora Project
  Built: 1773187200
  BuiltTime: Wed Mar 11 00:00:00 2026
  GitCommit: c6077f645788743258a1a749f8005b4fb3cbe533
  GoVersion: go1.25.7 X:nodwarf5
  Os: linux
  OsArch: linux/amd64
  Version: 5.8.1
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

I found it using podman version 4.9.3 on WSL with Ubuntu 24.04.4 LTS.
I tested it with the latest podman image to get the latest version. (using podman run on the above environment.)

### Additional information

The sting provided with `id=` does not matter.

### PR DESCRIPTION
**Pull request by Honny1**
Fixes: https://github.com/containers/podman/issues/28394

#### What type of PR is this?

> /kind api-change
> 
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Nice touchup, thanks @Honny1 !

**Comment by TomSweeneyRedHat** [comment]
Ooops, and
LGTM

File: pkg/parse/parse_test.go [hunk 1]
```diff
@@ -299,3 +300,64 @@ func TestGetBuildOutput(t *testing.T) {
...
+func TestSecrets(t *testing.T) {
+	errorTests := []struct {
+		name  string
+		input string
+	}{
+		{"bare-src-no-equals", "id=,src"},
+		{"bare-id-no-equals", "id"},
+		{"bare-src-key-no-equals", "src"},
+		{"bare-type-no-equals", "type"},
+		{"bare-env-no-equals", "env"},
```
Comment (danishprakash) [inline pkg/parse/parse_test.go]: Isn't the `strings.Cut` a loop-level check, in which case all four of these test the same code path. Though it might catch regressions in the future.

**Review by danishprakash — APPROVED** [review]

File: pkg/parse/parse_test.go (hunk 1 above)
Comment (Honny1) [reply pkg/parse/parse_test.go]: Yes, I will drop them. Good catch.

**Review by nalind — APPROVED** [review]
LGTM, thanks!

**Comment by TomSweeneyRedHat** [comment]
LGTM
