### PR TITLE
imagebuildah: consider ignorefile with --build-context

### LINKED ISSUE #4910: .containerignore files in additional build contexts are ignored
### Issue Description

When building images using multiple contexts (--build-context) there is no way to use .containerignore files to skip certain files from being COPYed.

Neither placing the .containerignore file in the main context nor in the additional context works.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run `podman build` using `--build-context=the_additional_context=somedir` to add a secondary build context.
2. Have some content in `somedir` directory, i.e. a Git repo with its `.git` directory.
3. Create `somedir/.containerignore` file with `**/.git` in order not to add it to the final image (or even **/*, it doesn't matter).
4. In Containerfile, `COPY` some content `--from=the_additional_context`.
5. Build and run a shell in the container and observe the COPYed directory, the .containerignore patterns were not honored.

### Describe the results you received

.containerignore patterns are ignored in respect of additional build contexts

### Describe the results you expected

.containerignore patterns are honored and ignored files are not COPYed

### podman info output

```yaml
$ podman info
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.6-1.module+el8.8.0+18098+9b44df5f.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: 8c4ab5a095127ecc96ef8a9c885e0e1b14aeb11b'
  cpuUtilization:
    idlePercent: 99.53
    systemPercent: 0.12
    userPercent: 0.35
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.8"
  eventLogger: file
  hostname: rhel8dev
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-477.13.1.el8_8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 965410816
  memTotal: 3811524608
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.4-1.module+el8.8.0+18060+3f21f2cc.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      spec: 1.0.2-dev
      go: go1.19.4
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_SYS_CHROOT,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.8.0+18060+3f21f2cc.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 193h 41m 17.00s (Approximately 8.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/fulvio/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/fulvio/.local/share/containers/storage
  graphRootAllocated: 37570478080
  graphRootUsed: 15538487296
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 251
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/fulvio/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1686839996
  BuiltTime: Thu Jun 15 16:39:56 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

RHEL 8 VM on RHV

### Additional information

.containerignore works properly when referring files coming from the main context, not from additional ones.

### PR DESCRIPTION
**Pull request by danishprakash**
Signed-off-by: danishprakash <danish.prakash@suse.com>

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:
Fixes #4910 

```release-note
None
```

### CODE REVIEW

File: imagebuildah/stage_executor.go [hunk 1]
```diff
@@ -412,6 +412,16 @@ func (s *StageExecutor) Copy(excludes []string, copies ...imagebuilder.Copy) err
...
+					} else {
+						// This points to a path on the filesystem
+						// Check to see if there's a .containerignore
+						// file, update excludes for this stage before
+						// proceeding
+						buildContextExcludes, _, err := parse.ContainerIgnoreFile(additionalBuildContext.Value, "", nil)
+						if err != nil {
+							return err
+						}
+						excludes = append(excludes, buildContextExcludes...)
```
Comment (TomSweeneyRedHat) [inline imagebuildah/stage_executor.go:424]: I'm on the fence and looking for other opinions.  Here: https://github.com/containers/buildah/blob/b90c36c7ed30af1cf04c0389e95b0515c8e6bef3/imagebuildah/stage_executor.go#L351 we have a couple of Debug lines to show what's being excluded.  I think it might be good to move those somewhere below this change.

Comment (danishprakash) [reply imagebuildah/stage_executor.go:424]: Sounds reasonable. Are you referring to this block inside `Copy()`?
```go
		if copy.Download {
			logrus.Debugf("ADD %#v, %#v", excludes, copy)
		} else {
			logrus.Debugf("COPY %#v, %#v", excludes, copy)
		}
```

**Review by flouthoc — APPROVED** [review]
Changes looks to good me, other than comment above.

**Comment by rhatdan** [comment]
@danishprakash still working on this one?

File: imagebuildah/stage_executor.go (hunk 1 above)
Comment (danishprakash) [reply imagebuildah/stage_executor.go:424]: bump! cc/ @rhatdan

Comment (danishprakash) [reply imagebuildah/stage_executor.go:419]: Moved it to the tail end of the loop just before we invoke the builder with opts.

**Comment by rhatdan** [comment]
/lgtm
Thanks @danishprakash
