### PR TITLE
COPY --exclude: make patterns context relative

### LINKED ISSUE #6726: `COPY --exclude=subdir app/ app/` doesn't exclude `app/subdir`
### Issue Description

When copying directory content, `buildah` expects `COPY --exclude` rule to include the dir itself.

### Steps to reproduce the issue

```
mkdir -p app/storage/cache
mkdir -p app/storage/views
```

```dockerfile
FROM ubuntu:24.04
COPY --exclude=storage/views app/ app/
RUN ls -la app/storage/
```

### Describe the results you received

Building this with `buildah` still adds `app/storage/views`.

```sh
$ buildah bud . 
STEP 1/3: FROM ubuntu:24.04
STEP 2/3: COPY --exclude=storage/views app/ app/
STEP 3/3: RUN ls -la app/storage
total 16
drwxr-xr-x. 4 root root 4096 Mar 12 17:52 .
drwxr-xr-x. 3 root root 4096 Mar 13 08:28 ..
drwxr-xr-x. 2 root root 4096 Mar 12 17:52 cache
drwxr-xr-x. 2 root root 4096 Mar 12 17:52 views
...
```

### Describe the results you expected

Building this with `docker` does not include `app/storage/views`.

```sh
$ docker build . --progress plain
...
#7 [2/3] COPY --exclude=storage/views app/ app/
#7 DONE 0.1s

#8 [3/3] RUN ls -la app/storage
#8 1.547 total 12
#8 1.547 drwxr-xr-x. 3 root root 4096 Mar 12 17:52 .
#8 1.547 drwxr-xr-x. 3 root root 4096 Mar 12 17:52 ..
#8 1.547 drwxr-xr-x. 2 root root 4096 Mar 13 08:33 cache
#8 DONE 2.2s
...
```

### buildah version output

```yaml
Version:         1.43.0
Go Version:      go1.25.6 X:nodwarf5
Image Spec:      1.1.1
Runtime Spec:    1.2.1
CNI Spec:        1.1.0
libcni Version:  
image Version:   5.39.1
Git Commit:      
Built:           Mon Feb  9 13:49:51 2026
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

### buildah info output

```yaml
Fedora 43 x64
```

### Provide your storage.conf

```toml
--
```

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Honny1**
Prepend each copy source to each exclude so source relative patterns match.

> Note: I found that the conformance tests ignore cases where the Buildah image contains more items than the Docker image. This is problematic for exclusion.

Fixes: https://github.com/containers/buildah/issues/6726

#### What type of PR is this?

> /kind api-change
> 
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
The `--exclude` flag: fix source relative pattern matching
```

### CODE REVIEW

File: tests/conformance/conformance_test.go [hunk 1]
```diff
@@ -2547,6 +2582,36 @@ var internalTestCases = []testCase{
...
+	{
+		// https://github.com/containers/buildah/issues/6726
+		name: "copy--exclude-subdir-under-source",
+		dockerfileContents: strings.Join([]string{
+			"# syntax=mirror.gcr.io/docker/dockerfile:1.9-labs",
+			"FROM scratch",
+			"COPY --exclude=storage/views app/ app/",
+		}, "\n"),
+		contextDir:          "dockerignore/exclude_subdir_under_source",
+		fsSkip:              []string{"(dir):app:mtime", "(dir):app:(dir):storage:mtime", "(dir):app:(dir):storage:(dir):cache:mtime"},
```
Comment (abitrolly) [inline tests/conformance/conformance_test.go]: What does `fsSkip` mean? Is it possible to replace it with human readable `ls -la` like output?

Comment (Honny1) [reply tests/conformance/conformance_test.go]: It skips specific file attributes or files when comparing container images. The conformance tests evaluate the differences between image builders, such as Buildah and Docker, by comparing the images they generate. In this case, it ignores the file mtime because those images might have been built at different times.

Comment (abitrolly) [reply tests/conformance/conformance_test.go]: Is there a reason to keep it array instead of multiline string? The array syntax is hard to read.

If `fsSkip` is for masking attributes and files, where is the place where comparison of unmasked content is being done?

**Comment by Honny1** [comment]
@nalind, I think PR is ready for review.

**Comment by TomSweeneyRedHat** [comment]
@nalind PTAL
LGTM

File: imagebuildah/stage_executor.go [hunk 2]
```diff
@@ -374,6 +374,16 @@ func (s *stageExecutor) Copy(excludes []string, copies ...imagebuilder.Copy) err
 		}
 		if len(cp.Excludes) > 0 {
 			excludes = append(slices.Clone(excludes), cp.Excludes...)
+			for _, src := range cp.Src {
+				srcNorm := path.Clean(filepath.ToSlash(src))
+				for _, excl := range cp.Excludes {
+					if srcNorm == "." || srcNorm == "" {
```
Comment (nalind) [inline imagebuildah/stage_executor.go]: When is `srcNorm` empty?

File: tests/conformance/conformance_test.go [hunk 3]
```diff
@@ -2541,10 +2559,43 @@ var internalTestCases = []testCase{
...
+	{
+		// https://github.com/containers/buildah/issues/6726
+		name: "copy--exclude-subdir-under-source",
+		dockerfileContents: strings.Join([]string{
+			"# syntax=mirror.gcr.io/docker/dockerfile:1.9-labs",
+			"FROM scratch",
+			"COPY --exclude=storage/views app/ app/",
+		}, "\n"),
+		contextDir:           "dockerignore/exclude_subdir_under_source",
+		fsSkip:               []string{"(dir):app:mtime", "(dir):app:(dir):storage:mtime", "(dir):app:(dir):storage:(dir):cache:mtime"},
```
Comment (nalind) [inline tests/conformance/conformance_test.go]: "storage" and "storage/cache" should come from the build context directory, so they shouldn't be expected to have different mtimes.

File: imagebuildah/stage_executor.go (hunk 2 above)
Comment (nalind) [inline imagebuildah/stage_executor.go]: When is `srcNorm` empty?

File: tests/conformance/conformance_test.go [hunk 4]
```diff
@@ -2541,10 +2559,43 @@ var internalTestCases = []testCase{
...
+		name: "copy--form-and--exclude-subdir-under-source",
+		dockerfileContents: strings.Join([]string{
+			"# syntax=mirror.gcr.io/docker/dockerfile:1.9-labs",
+			"FROM scratch as base",
+			"COPY . .",
+			"FROM scratch",
+			"COPY --from=base --exclude=storage/views app/ app/",
+		}, "\n"),
+		contextDir:           "dockerignore/exclude_subdir_under_source",
+		fsSkip:               []string{"(dir):app:mtime", "(dir):app:(dir):storage:mtime", "(dir):app:(dir):storage:(dir):cache:mtime"},
```
Comment (nalind) [inline tests/conformance/conformance_test.go]: "storage" and "storage/cache" should ultimately come from the build context directory, so they shouldn't be expected to have different mtimes.

File: imagebuildah/stage_executor.go [hunk 5]
```diff
@@ -374,6 +374,16 @@ func (s *stageExecutor) Copy(excludes []string, copies ...imagebuilder.Copy) err
...
+						excludes = append(excludes, excl)
+					} else {
+						excludes = append(excludes, path.Join(srcNorm, excl))
```
Comment (nalind) [inline imagebuildah/stage_executor.go]: Exclusion patterns can be reversed (made exceptions to exclusion patterns) by prefixing them with `!`.  Does this have the intended result if a subdirectory is excluded, but one of its subdirectories is then made an exception?

**Review by nalind — CHANGES_REQUESTED** [review]
A couple of tweaks to the filesystem exceptions in the conformance tests, and I'm not sure that exceptions to exclusions are being handled properly.

**Comment by abitrolly** [comment]
I remember there was also an issue that `podman` didn't set new permissions when overwriting subdirs in consequent COPY. That's why I had to use `--exclude` (which didn't help).

Now I have this in Docker. to set write access. without `--exclude`. I haven't tested that it works the same way with `podman`.
```
COPY app/ app/
RUN ls -la app/storage
# copy write enabled dirs separately to set correct permissions
COPY --parents --chown=ubuntu:ubuntu \
     app/storage \
     ./
```

**Comment by Honny1** [comment]
> I remember there was also an issue that `podman` didn't set new permissions when overwriting subdirs in consequent COPY. That's why I had to use `--exclude` (which didn't help).
> 
> Now I have this in Docker. to set write access. without `--exclude`. I haven't tested that it works the same way with `podman`.
> 
> ```
> COPY app/ app/
> RUN ls -la app/storage
> # copy write enabled dirs separately to set correct permissions
> COPY --parents --chown=ubuntu:ubuntu \
>      app/storage \
>      ./
> ```

I think this is unrelated to this PR.

**Comment by Honny1** [comment]
@nalind PTAL, I have addressed your comments.

**Review by nalind — APPROVED** [review]
LGTM, thanks!

**Comment by Honny1** [comment]
PTAL @containers/buildah-maintainers

**Review by giuseppe — APPROVED** [review]
LGTM
