### PR TITLE
Skip tlsVerify insecure BUILD_REGISTRY_SOURCES

### LINKED ISSUE #2586: insecureRegistries from BUILD_REGISTRY_SOURCES ignored
**Description**

`insecureRegistries` from the `BUILD_REGISTRY_SOURCES` env. var. is ignored.

There's nothing in the source that actually handles this key AFAICS - the only reference is https://github.com/containers/buildah/blob/master/commit.go#L186.

The `insecureRegistries` key is mentioned in e.g. `man buildah-pull` and `man buildah-push`. At a minimum the documentation should mention that the key is currently non-functional.

**Steps to reproduce the issue:**

```
BUILD_REGISTRY_SOURCES='{"insecureRegistries": ["<registry>"]}' buildah push <img> <registry>/<img>
```

**Describe the results you received:**

```
Get "https://<registry>/v2/": http: server gave HTTP response to HTTPS client
ERRO exit status 125
```

**Describe the results you expected:**

Successful push to registry.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.15.1-1.fc32.x86_64
```

### PR DESCRIPTION
**Pull request by QiWang19**
If the registry is set to insecure allowd using BUILD_REGISTRY_SOURCES, hardcode to skip the tls verify to avoid the errors.
Returns error if set insecureRegistries but force to use tls-verify.

Signed-off-by: Qi Wang <qiwan@redhat.com>

#### What type of PR is this?

> /kind bug

close #2586 
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: commit.go [hunk 1]
```diff
@@ -278,9 +281,18 @@ func (b *Builder) Commit(ctx context.Context, dest types.ImageReference, options
...
 
 	// Check if the commit is blocked by $BUILDER_REGISTRY_SOURCES.
-	if err := checkRegistrySourcesAllows("commit to", dest); err != nil {
+	insecure, err := checkRegistrySourcesAllows("commit to", dest)
+	if err != nil {
 		return imgID, nil, "", err
 	}
+	if insecure {
+		if systemContext.DockerInsecureSkipTLSVerify == types.OptionalBoolFalse {
+			return imgID, nil, "", errors.Errorf("can't require tls verify on insecurely allowed registry")
```
Comment (TomSweeneyRedHat) [inline commit.go:290]:
```suggestion
			return imgID, nil, "", errors.Errorf("can't require tls verification on an insecured registry")
```

File: commit.go [hunk 2]
```diff
@@ -291,9 +303,18 @@ func (b *Builder) Commit(ctx context.Context, dest types.ImageReference, options
...
 				return imgID, nil, "", errors.Wrapf(err, "error parsing image name %q as an image reference", name)
 			}
-			if err := checkRegistrySourcesAllows("commit to", additionalDest); err != nil {
+			insecure, err := checkRegistrySourcesAllows("commit to", additionalDest)
+			if err != nil {
 				return imgID, nil, "", err
 			}
+			if insecure {
+				if systemContext.DockerInsecureSkipTLSVerify == types.OptionalBoolFalse {
+					return imgID, nil, "", errors.Errorf("can't require tls verify on insecurely allowed registry")
```
Comment (TomSweeneyRedHat) [inline commit.go:312]:
```suggestion
					return imgID, nil, "", errors.Errorf("can't require tls verification on an insecured registry")
```

File: commit.go [hunk 3]
```diff
@@ -471,9 +492,18 @@ func Push(ctx context.Context, image string, dest types.ImageReference, options
...
 
 	// Check if the push is blocked by $BUILDER_REGISTRY_SOURCES.
-	if err := checkRegistrySourcesAllows("push to", dest); err != nil {
+	insecure, err := checkRegistrySourcesAllows("push to", dest)
+	if err != nil {
 		return nil, "", err
 	}
+	if insecure {
+		if systemContext.DockerInsecureSkipTLSVerify == types.OptionalBoolFalse {
+			return nil, "", errors.Errorf("can't require tls verify on insecurely allowed registry")
```
Comment (TomSweeneyRedHat) [inline commit.go:501]:
```suggestion
			return nil, "", errors.Errorf("can't require tls verification on an insecured registry")
```

File: pull.go [hunk 4]
```diff
@@ -238,9 +238,18 @@ func pullImage(ctx context.Context, store storage.Store, srcRef types.ImageRefer
...
 		return nil, errors.Errorf("pull access to registry for %q is blocked by configuration", transports.ImageName(srcRef))
 	}
-	if err := checkRegistrySourcesAllows("pull from", srcRef); err != nil {
+	insecure, err := checkRegistrySourcesAllows("pull from", srcRef)
+	if err != nil {
 		return nil, err
 	}
+	if insecure {
+		if sc.DockerInsecureSkipTLSVerify == types.OptionalBoolFalse {
+			return nil, errors.Errorf("can't require tls verify on insecurely allowed registry")
```
Comment (TomSweeneyRedHat) [inline pull.go:247]:
```suggestion
			return nil, errors.Errorf("can't require tls verification on an insecured registry")
```

File: commit.go (hunk 1 above)
Comment (TomSweeneyRedHat) [reply commit.go:290]: It doesn't look like we document in the man pages.  We might want to add something like: "This option cannot be used when talking to an insecure registry." in the verbiage for the tls-verify option for each of these.

File: commit.go [hunk 5]
```diff
@@ -167,17 +167,17 @@ var (
 // variable, if it's set.  The contents are expected to be a JSON-encoded
 // github.com/openshift/api/config/v1.Image, set by an OpenShift build
 // controller that arranged for us to be run in a container.
-func checkRegistrySourcesAllows(forWhat string, dest types.ImageReference) error {
+func checkRegistrySourcesAllows(forWhat string, dest types.ImageReference) (bool, error) {
```
Comment (TomSweeneyRedHat) [inline commit.go:170]: Just for clarity, it might be good to name the return values if gofmt allows:
```suggestion
func checkRegistrySourcesAllows(forWhat string, dest types.ImageReference) (insecure bool, err error) {
```

File: tests/push.bats [hunk 6]
```diff
@@ -181,6 +181,16 @@ load helpers
   rm -rf ${TESTDIR}/tmp
 }
 
+@test "buildah push to registry allowed by BUILD_REGISTRY_SOURCES" {
+  _prefetch busybox
+  export BUILD_REGISTRY_SOURCES='{"insecureRegistries": ["localhost:5000"]}'
+
+  run_buildah 125 push --creds testuser:testpassword  --signature-policy ${TESTSDIR}/policy.json --tls-verify=true busybox docker://localhost:5000/buildah/busybox:latest
+  expect_output --substring "can't require tls verify on insecurely allowed registry"
```
Comment (TomSweeneyRedHat) [inline tests/push.bats:189]: this will need to change if you take the rewording.

File: commit.go (hunk 1 above)
Comment (QiWang19) [reply commit.go:290]: Change to `TLS verification cannot be used when talking to an insecure registry.`, since the option --tls-verify=false is allowed if using insecure registry.

File: docs/buildah-bud.md [hunk 7]
```diff
@@ -467,7 +467,7 @@ Commands after the target stage will be skipped.
 
 **--tls-verify** *bool-value*
 
-Require HTTPS and verify certificates when talking to container registries (defaults to true).
+Require HTTPS and verify certificates when talking to container registries (defaults to true).  TLS verification cannot be used when talking to an insecure registry.
```
Comment (TomSweeneyRedHat) [inline docs/buildah-bud.md:470]: Nicely stated @QiWang19

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 looks like you need a rebase.

**Comment by QiWang19** [comment]
@containers/podman-maintainers PTAL
